### ISSUE TITLE
Float not iterable

### ISSUE THREAD

**Issue by ghost** [kurtsenol/machine-learning#1]
Hi, I tried to run your notebook with your data but in line 16 it raises the error
TypeError: 'float' object is not iterable
did it run through with same notebook and set of data?
thank you
roman

**Comment by kurtsenol** [comment]
You mean the cell building bi-grams and tri-grams, right?
Yes, it ran without any problem.

**Comment by ghost** [comment]
Hi Kurt, 
thank you for your fast reply. How does it come, that you used papers from the tourism sector for your analysis? Are you in this field as well? 

Actually this is the error when I use my data. 




If I use your data it passes this section, but raises another error 

would be happy to stay in contact with you 
Regards 
Roman 


****************************************************************************** 
FACHHOCHSCHULE SALZBURG GmbH 
Salzburg University of Applied Sciences 

FH-Prof. Dr. Roman Egger 
Department Innovation and Management in Tourism 

Head of Research 
Head of eTourism 

Urstein Süd 1 
A-5412 Puch bei Salzburg 
Tel: +43 (0)50 2211-1357 
Fax: +43 (0)50 2211-1399 

ORCID: 0000-0003-4888-6026 

Visit us at: www.etourism-students.com 
www.virtual-reality-in-tourism.com 

See my series " [ https://www.springer.com/series/13605 | Tourism on the Verge ] "; Springer 


Von: "Senol Kurt" <notifications@github.com> 
An: "kurtsenol/machine-learning" <machine-learning@noreply.github.com> 
CC: "DS-in-Tourism" <roman.egger@fh-salzburg.ac.at>, "Author" <author@noreply.github.com> 
Gesendet: Samstag, 29. August 2020 22:55:28 
Betreff: [EXTERNAL] Re: [kurtsenol/machine-learning] Float not iterable (#1) 






You mean the cell building bi-grams and tri-grams, right? 
Yes, it ran without any problem.

**Comment by kurtsenol** [comment]
I currently do my PhD in business management. If you send the details about the error you got, I can try to help you.

**Comment by ghost** [comment]
Hi Kurt, 
can you send me your proper eMail? 
Regards 
Roman 

****************************************************************************** 
FACHHOCHSCHULE SALZBURG GmbH 
Salzburg University of Applied Sciences 

FH-Prof. Dr. Roman Egger 
Department Innovation and Management in Tourism 

Head of Research 
Head of eTourism 

Urstein Süd 1 
A-5412 Puch bei Salzburg 
Tel: +43 (0)50 2211-1357 
Fax: +43 (0)50 2211-1399 

ORCID: 0000-0003-4888-6026 

Visit us at: www.etourism-students.com 
www.virtual-reality-in-tourism.com 

See my series " [ https://www.springer.com/series/13605 | Tourism on the Verge ] "; Springer 


Von: "Senol Kurt" <notifications@github.com> 
An: "kurtsenol/machine-learning" <machine-learning@noreply.github.com> 
CC: "DS-in-Tourism" <roman.egger@fh-salzburg.ac.at>, "Author" <author@noreply.github.com> 
Gesendet: Sonntag, 30. August 2020 13:45:18 
Betreff: [EXTERNAL] Re: [kurtsenol/machine-learning] Float not iterable (#1) 





I currently do my PhD in business management. If you send the details about the error you got, I can try to help you. 

— 
You are receiving this because you authored the thread. 
Reply to this email directly, [ https://secure-web.cisco.com/1TMVMNFhwZpCqbLX2cxMhqO6H4xuW0n131QhJVNSqZdDGO0gMJYcWPpRZkpXkfohjmc0LA-mj1kBlmf5RO4dBB0DqOFtsddhi9LZ9YC4kfkSv2rVU_r73GwnZK0tEcxNSiHle4Cehosioz7rOIhxSQV0QPYYtKtJRA8fPN-CFP4xVcr-Ag1Nm2EFtBonbjlTtwaF02mNGIFSIWG37kM_c0lYnrYpzjzY3Yy6o6W2qKtvCIqiz8cBrNK3cyOVXO_YK/https%3A%2F%2Fgithub.com%2Fkurtsenol%2Fmachine-learning%2Fissues%2F1%23issuecomment-683410545 | view it on GitHub ] , or [ https://secure-web.cisco.com/1JSVX9kLiQP3OKPBbG64Whi7l877W9gOKuBQ9SH3pLZt0eJkDZ9FJqlduFm0qQrT7dC2h8yZYOjxtbwkNkJtj7q1nVj1YNbEnWBuV3YfdrDBuxUFJfpyl4S1awtzFN417sg4rO_kpefchESd-dZFxqSrF68zBDDhbq0VsxKVtSuNsngAaw9JZ7R4ykbulpGNLHKJyAJG-dswtLmBWIY9Mz_-QSS-ILuRo2Q0KawS5ZY2ZqxKpect3fAzECG-eyGxe/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQYTKULA3WHFZVJX4RM55OTSDI3U5ANCNFSM4QPDMR5Q | unsu
 bscribe ] .

**Comment by kurtsenol** [comment]
kurtsenol21@gmail.com
